/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface RenderSprite {
        "frameCoord": string;
        "image": CanvasImageSource;
        "size": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRenderSpriteElement extends Components.RenderSprite, HTMLStencilElement {
    }
    var HTMLRenderSpriteElement: {
        prototype: HTMLRenderSpriteElement;
        new (): HTMLRenderSpriteElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "render-sprite": HTMLRenderSpriteElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface RenderSprite {
        "frameCoord"?: string;
        "image"?: CanvasImageSource;
        "size"?: number;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "render-sprite": RenderSprite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "render-sprite": LocalJSX.RenderSprite & JSXBase.HTMLAttributes<HTMLRenderSpriteElement>;
        }
    }
}
